services:
  app:
    build:
      context: .
      target: dev
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chatdb?sslmode=disable
      - PORT=8080
      - SECRET_KEY=insecure-key
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chatdb
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
